apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: jaga1996/ci_cd_learning:ecommerce-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
