apiVersion: v1
kind: Service
metadata:
  name: my-first-k8s-services-file
spec:
  selector: # Pods Info
    app: my-first-k8s-pod # Checks for pod with name my-first-k8s-pod
  ports:
  - port: 8501
    targetPort: 8501
  type: LoadBalancer
