name: Data Validator Actions file

on:
  push:
    branches:
      - main
      - temp_branch
  pull_request:
    branches:
       - main
       - temp_branch

jobs:
    data-validation-pipeline:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.2'

        - name: Install Libraries
          run: pip install pandas datetime
        
        - name: Run the Script
          run: python3 github_actions/data_validation_pipeline.py

        - name: Push the log file to github repo
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Update validation logs" || echo "No changes to commit"
            git push